In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3], [4, 5, 6]])
b = np.array([[1,21,13], [3, 2, 1]])

In [6]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [15]:
c =np.sum([a, b], axis = 0)

In [16]:
print(c)

[[ 2 23 16]
 [ 7  7  7]]


In [17]:
print(c)

[[ 2 23 16]
 [ 7  7  7]]


In [18]:
list_array = list()

In [19]:
list_array.append(a)
list_array.append(b)
print(list_array)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 1, 21, 13],
       [ 3,  2,  1]])]


In [27]:
list_array_scaled = np.array(list_array) * 0.2
print(list_array_scaled)

[[[0.2 0.4 0.6]
  [0.8 1.  1.2]]

 [[0.2 4.2 2.6]
  [0.6 0.4 0.2]]]


In [24]:
a * 0.3

array([[0.3, 0.6, 0.9],
       [1.2, 1.5, 1.8]])